Repository MONEYMONG/Android-Moneymong, pull requests merged in 2024-10, with the labels that each got.

#34 Feature/moneymong 509 장부 내역 기간별 조회 이슈 수정
  core/design-system/src/main/java/com/moneymong/moneymong/design_system/component/datepicker/MDSBottomSheetDatePicker.kt
  feature/ledger/src/main/java/com/moneymong/moneymong/ledger/LedgerViewModel.kt
Labels: highest❤️

#37 feat: 장부 수동등록 메모 영역 위치 변경
  feature/ledgermanual/src/main/java/com/moneymong/moneymong/ledgermanual/LedgerManualScreen.kt
Labels: medium💛

#38 Moneymong 511 강제 업데이트 얼랏창 구현
  app/build.gradle.kts
  app/src/main/java/com/moneymong/moneymong/MainActivity.kt
  app/src/main/java/com/moneymong/moneymong/MainState.kt
  app/src/main/java/com/moneymong/moneymong/MainViewModel.kt
  core/design-system/src/main/java/com/moneymong/moneymong/design_system/error/ErrorDialog.kt
  core/model/src/main/java/com/moneymong/moneymong/model/version/VersionRequest.kt
  core/network/src/main/java/com/moneymong/moneymong/network/adapter/ResultCallAdapter.kt
  core/network/src/main/java/com/moneymong/moneymong/network/api/MoneyMongApi.kt
  core/network/src/main/java/com/moneymong/moneymong/network/api/VersionApi.kt
  core/network/src/main/java/com/moneymong/moneymong/network/di/NetworkModule.kt
  core/network/src/main/java/com/moneymong/moneymong/network/response/ErrorResponse.kt
  core/network/src/main/java/com/moneymong/moneymong/network/util/AuthInterceptor.kt
  core/network/src/main/java/com/moneymong/moneymong/network/util/MoneyMongTokenAuthenticator.kt
  core/ui/src/main/java/com/moneymong/moneymong/ui/RippleEffect.kt
  data/src/main/java/com/moneymong/moneymong/data/datasource/version/VersionRemoteDataSource.kt
  data/src/main/java/com/moneymong/moneymong/data/datasource/version/VersionRemoteDataSourceImpl.kt
  data/src/main/java/com/moneymong/moneymong/data/di/DataSourceModule.kt
  data/src/main/java/com/moneymong/moneymong/data/di/RepositoryModule.kt
  data/src/main/java/com/moneymong/moneymong/data/repository/agency/AgencyRepositoryImpl.kt
  data/src/main/java/com/moneymong/moneymong/data/repository/signup/UnivRepositoryImpl.kt
  data/src/main/java/com/moneymong/moneymong/data/repository/token/TokenRepositoryImpl.kt
  data/src/main/java/com/moneymong/moneymong/data/repository/version/VersionRepositoryImpl.kt
  domain/src/main/java/com/moneymong/moneymong/domain/repository/agency/AgencyRepository.kt
  domain/src/main/java/com/moneymong/moneymong/domain/repository/token/TokenRepository.kt
  domain/src/main/java/com/moneymong/moneymong/domain/repository/univ/UnivRepository.kt
  domain/src/main/java/com/moneymong/moneymong/domain/repository/version/VersionRepository.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/agency/AgencyJoinUseCase.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/agency/FetchAgencyIdUseCase.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/agency/FetchMyAgencyListUseCase.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/agency/GetAgenciesUseCase.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/agency/RegisterAgencyUseCase.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/agency/SaveAgencyIdUseCase.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/signup/SchoolInfoUseCase.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/token/PostAccessTokenUseCase.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/token/TokenUseCase.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/university/CreateUniveristyUseCase.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/university/FetchMyUniversityUseCase.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/university/SearchUniversityUseCase.kt
  domain/src/main/java/com/moneymong/moneymong/domain/usecase/version/CheckVersionUpdateUseCase.kt
  feature/ledger/src/main/java/com/moneymong/moneymong/ledger/view/LedgerAgencyEmptyView.kt
  feature/ledger/src/main/java/com/moneymong/moneymong/ledger/view/onboarding/LedgerOnboardingAddPage.kt
  feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SplashScreen.kt
  gradle/libs.versions.toml
Labels: high🧡
